name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SDK Version
      description: Which version are you using? (e.g., 6.0, 2.0)
      placeholder: 6.0.0
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language
      options:
        - C
        - Rust
        - Go
        - Java
        - Node.js
        - C#
        - Python
        - PHP
    validations:
      required: true
