/*
 * QZDB reference-compliant benchmark for C  (docs/BENCH_CONTRACT.md v1.0)
 *
 * Implements:
 *   - splitmix64 reference RNG (byte-identical to the 7 other language benches)
 *   - four distributions: random / hot / sequential / real_world
 *   - dual-stack tri-mode: v4 / v6 / mixed(50-40-10)
 *   - QPS / avg / P50 / P95 / P99, cold vs hot
 *   - thread scaling 1/2/4/8/16 on ONE shared reader  + 16x100k concurrency gate
 *   - canonical JSON -> multi-lang/bench_reports/c_<edition>.json
 *
 * Parity guard: the FNV-1a 64 of the first 1024 queries of every stream is
 * compared against the value baked into bench_vectors.h (generated by
 * tools/bench_gen.py from the same manifest the other languages read). A match
 * proves the whole 2M-query stream is byte-identical to Python's, by
 * construction.
 *
 * C has a fill-only, immutable, lock-free decode cache (see qzdb_reader.h), so
 * unlike the managed runtimes its shared-reader thread scaling should stay
 * near-linear. That contrast is exactly what this contract exists to surface.
 *
 * Env overrides:  BENCH_OPS=200000   BENCH_EDITIONS=std_china
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <math.h>
#include <pthread.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/sysctl.h>
#include "qzdb_reader.h"
#include "../tools/bench_vectors.h"

/* ----------------------------------------------------------- constants */

#define D_RANDOM       0
#define D_HOT          1
#define D_SEQ          2
#define D_REALWORLD    3
#define M_V4           0
#define M_V6           1
#define M_MIXED        2

static const char *DIST_NAMES[4] = {"random", "hot", "sequential", "real_world"};
static const char *MODE_NAMES[3] = {"v4", "v6", "mixed"};

#define COLD_OPS       200000
#define WARMUP_OPS     1000000
#define LAT_EVERY      20
#define CONC_THREADS   16
#define CONC_OPS       100000
#define MAPPED_PREFIX_LO 0x0000FFFF00000000ULL

static int g_ops = 2000000;

/* ----------------------------------------------------------- splitmix64 */

static uint64_t sm_next(uint64_t *s) {
    *s += 0x9E3779B97F4A7C15ULL;
    uint64_t z = *s;
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
    return z ^ (z >> 31);
}
static uint32_t sm_u32(uint64_t *s) { return (uint32_t)sm_next(s); }

/* ----------------------------------------------------------- pools */

static uint32_t g_pool_v4[QZDB_BENCH_POOL_V4];
static uint64_t g_pool_v6_hi[QZDB_BENCH_POOL_V6];
static uint64_t g_pool_v6_lo[QZDB_BENCH_POOL_V6];

static void build_pools(void) {
    uint64_t s = QZDB_BENCH_MASTER_SEED + 1;
    for (int i = 0; i < QZDB_BENCH_POOL_V4; i++) g_pool_v4[i] = sm_u32(&s);
    s = QZDB_BENCH_MASTER_SEED + 2;
    for (int i = 0; i < QZDB_BENCH_POOL_V6; i++) {
        g_pool_v6_hi[i] = sm_next(&s);
        g_pool_v6_lo[i] = sm_next(&s);
    }
}

/* ----------------------------------------------------------- stream */

typedef struct {
    uint64_t rng;
    int dist, mode;
    uint32_t base4;
    uint64_t base6_hi, base6_lo;
    uint64_t i;
} stream_t;

static void stream_init(stream_t *st, int dist, int mode, uint64_t seed) {
    st->dist = dist; st->mode = mode;
    st->rng = seed;
    st->base4 = sm_u32(&st->rng);
    st->base6_hi = sm_next(&st->rng);
    st->base6_lo = sm_next(&st->rng);
    st->i = 0;
}

static uint32_t gen_v4(stream_t *st) {
    switch (st->dist) {
    case D_RANDOM:  return sm_u32(&st->rng);
    case D_HOT:     return g_pool_v4[sm_u32(&st->rng) % QZDB_BENCH_POOL_V4];
    case D_SEQ:     return st->base4 + (uint32_t)st->i;          /* wraps mod 2^32 */
    default: {                                                   /* real_world */
        uint32_t r = sm_u32(&st->rng) % 10;
        if (r < 6) return g_pool_v4[sm_u32(&st->rng) % QZDB_BENCH_POOL_V4];
        if (r < 9) return sm_u32(&st->rng);
        return st->base4 + (uint32_t)st->i;
    }
    }
}

static void add128(uint64_t hi, uint64_t lo, uint64_t inc,
                   uint64_t *ohi, uint64_t *olo) {
    uint64_t t = lo + inc;
    uint64_t carry = (t < lo) ? 1 : 0;
    *olo = t;
    *ohi = hi + carry;
}

static void gen_v6(stream_t *st, uint64_t *hi, uint64_t *lo) {
    switch (st->dist) {
    case D_RANDOM:
        *hi = sm_next(&st->rng); *lo = sm_next(&st->rng); return;
    case D_HOT: {
        int idx = (int)(sm_u32(&st->rng) % QZDB_BENCH_POOL_V6);
        *hi = g_pool_v6_hi[idx]; *lo = g_pool_v6_lo[idx]; return;
    }
    case D_SEQ:
        add128(st->base6_hi, st->base6_lo, st->i, hi, lo); return;
    default: {                                                   /* real_world */
        uint32_t r = sm_u32(&st->rng) % 10;
        if (r < 6) {
            int idx = (int)(sm_u32(&st->rng) % QZDB_BENCH_POOL_V6);
            *hi = g_pool_v6_hi[idx]; *lo = g_pool_v6_lo[idx]; return;
        }
        if (r < 9) { *hi = sm_next(&st->rng); *lo = sm_next(&st->rng); return; }
        add128(st->base6_hi, st->base6_lo, st->i, hi, lo); return;
    }
    }
}

/* produce the i-th query; mirrors bench_gen.gen_stream() exactly (RNG draw order) */
static void stream_next(stream_t *st, int *kind, uint64_t *hi, uint64_t *lo) {
    switch (st->mode) {
    case M_V4:
        *kind = 0; *hi = gen_v4(st); *lo = 0; break;
    case M_V6:
        if (sm_u32(&st->rng) % 5 == 0) {                         /* 80/20 mapped */
            uint32_t ip = gen_v4(st);
            *kind = 2; *hi = 0; *lo = MAPPED_PREFIX_LO | (uint64_t)ip;
        } else {
            gen_v6(st, hi, lo); *kind = 1;
        }
        break;
    default: {                                                   /* mixed 50/40/10 */
        uint64_t m = st->i % 10;
        if (m < 5)      { *kind = 0; *hi = gen_v4(st); *lo = 0; }
        else if (m < 9) { gen_v6(st, hi, lo); *kind = 1; }
        else            { uint32_t ip = gen_v4(st); *kind = 2; *hi = 0;
                          *lo = MAPPED_PREFIX_LO | (uint64_t)ip; }
        break;
    }
    }
    st->i++;
}

/* ----------------------------------------------------------- fnv1a + encoding */

static uint64_t fnv1a(const uint8_t *b, int n, uint64_t h) {
    if (h == 0) h = 0xCBF29CE484222325ULL;
    for (int i = 0; i < n; i++) {
        h ^= b[i];
        h *= 0x100000001B3ULL;
    }
    return h;
}

static void enc_query(int kind, uint64_t hi, uint64_t lo, uint8_t *out, int *len) {
    if (kind == 0) {
        uint32_t ip = (uint32_t)hi;
        for (int k = 0; k < 4; k++) out[k] = (ip >> (8 * k)) & 0xFF;
        for (int k = 4; k < 8; k++) out[k] = 0;
        *len = 8;
    } else {
        for (int k = 0; k < 8; k++) out[k] = (hi >> (8 * k)) & 0xFF;
        for (int k = 0; k < 8; k++) out[8 + k] = (lo >> (8 * k)) & 0xFF;
        *len = 16;
    }
}

/* ----------------------------------------------------------- metrics */

typedef struct {
    int      ops;
    double   qps;
    double   avg_ns;
    int64_t  p50_ns, p95_ns, p99_ns;
    int64_t  errs;
    int64_t  hits;
    double   hit_rate;
    const char *warm;
    const char *api;
} metrics_t;

static int cmp_i64(const void *a, const void *b) {
    int64_t x = *(const int64_t *)a, y = *(const int64_t *)b;
    return (x > y) - (x < y);
}
static int64_t pct(int64_t *v, int n, double p) {
    if (n == 0) return 0;
    qsort(v, n, sizeof(int64_t), cmp_i64);
    int idx = (int)(floor((double)n * p + 0.9999)) - 1;
    if (idx < 0) idx = 0;
    if (idx >= n) idx = n - 1;
    return v[idx];
}

static void now_ns(struct timespec *ts) {
    clock_gettime(CLOCK_MONOTONIC, ts);
}
static double since_ns(struct timespec *t0) {
    struct timespec t1; clock_gettime(CLOCK_MONOTONIC, &t1);
    return (double)(t1.tv_sec - t0->tv_sec) * 1e9 + (double)(t1.tv_nsec - t0->tv_nsec);
}

/* dispatch returns hit (rc==0) and error flag.
 * QZDB_ERR_NOT_FOUND (-1) is an EXPECTED miss, NOT a decode error — the
 * concurrency gate and the error counters must not count it. */
static int is_real_error(int rc) {
    return (rc != 0 && rc != QZDB_ERR_NOT_FOUND);
}
static int dispatch(qzdb_reader_t *ctx, int kind, uint64_t hi, uint64_t lo, int *hit) {
    qzdb_geo_info_t info;
    int rc;
    if (kind == 0) {
        rc = qzdb_find_uint(ctx, (uint32_t)hi, &info);
    } else {
        uint8_t bin[16];
        for (int k = 0; k < 8; k++) bin[k]     = (hi >> (8 * (7 - k))) & 0xFF;
        for (int k = 0; k < 8; k++) bin[8 + k] = (lo >> (8 * (7 - k))) & 0xFF;
        /* kind 2 is IPv4-mapped (::ffff:w.x.y.z) and MUST use the
         * mapped-aware entry: qzdb_find_v6() is a pure v6 trie walk that
         * never downgrades, so it misses on every mapped query and the
         * bench would time the early-exit miss path, not a real lookup. */
        rc = (kind == 2) ? qzdb_find_bytes(ctx, bin, &info)
                         : qzdb_find_v6(ctx, bin, &info);
    }
    *hit = (rc == 0);
    return rc;
}

static metrics_t run_single(qzdb_reader_t *ctx, int dist, int mode, uint64_t seed,
                            int ops, int sample) {
    stream_t st; stream_init(&st, dist, mode, seed);
    int64_t *lat = NULL; int lcap = 0;
    if (sample) { lcap = ops / LAT_EVERY + 1; lat = malloc(lcap * sizeof(int64_t)); }
    int64_t errs = 0, hits = 0, lcnt = 0;
    struct timespec t0; now_ns(&t0);
    for (int i = 0; i < ops; i++) {
        int kind; uint64_t hi, lo;
        stream_next(&st, &kind, &hi, &lo);
        int hit = 0;
        if (sample && i % LAT_EVERY == 0) {
            struct timespec a; now_ns(&a);
            int e = dispatch(ctx, kind, hi, lo, &hit);
            int64_t dt = (int64_t)since_ns(&a);
            if (lcnt < lcap) lat[lcnt++] = dt;
            if (is_real_error(e)) errs++;
            if (hit) hits++;
        } else {
            int e = dispatch(ctx, kind, hi, lo, &hit);
            if (is_real_error(e)) errs++;
            if (hit) hits++;
        }
    }
    double el = since_ns(&t0);
    metrics_t m;
    m.ops = ops;
    m.qps = (double)ops / (el / 1e9);
    m.avg_ns = el / (double)ops;
    m.p50_ns = pct(lat, lcnt, 0.50);
    m.p95_ns = pct(lat, lcnt, 0.95);
    m.p99_ns = pct(lat, lcnt, 0.99);
    m.errs = errs; m.hits = hits;
    m.hit_rate = (double)hits / (double)ops;
    m.warm = ""; m.api = "uint";
    free(lat);
    return m;
}

/* ----------------------------------------------------------- threads */

typedef struct {
    qzdb_reader_t *ctx;
    stream_t st;
    int      ops;
    int64_t  done, hits, errs;
} targ_t;

static void *thread_run(void *arg) {
    targ_t *t = (targ_t *)arg;
    for (int i = 0; i < t->ops; i++) {
        int kind; uint64_t hi, lo;
        stream_next(&t->st, &kind, &hi, &lo);
        int hit = 0;
        int e = dispatch(t->ctx, kind, hi, lo, &hit);
        t->done++;
        if (is_real_error(e)) t->errs++;
        if (hit) t->hits++;
    }
    return NULL;
}

static metrics_t run_multi(qzdb_reader_t *ctx, int dist, int mode, uint64_t seed,
                           int threads, int ops) {
    int per = ops / threads;
    targ_t *args = calloc(threads, sizeof(targ_t));
    pthread_t *th = calloc(threads, sizeof(pthread_t));
    for (int i = 0; i < threads; i++) {
        stream_init(&args[i].st, dist, mode, seed);
        args[i].ctx = ctx;
        args[i].ops = per;
        args[i].done = args[i].hits = args[i].errs = 0;
    }
    struct timespec t0; now_ns(&t0);
    for (int i = 0; i < threads; i++) pthread_create(&th[i], NULL, thread_run, &args[i]);
    for (int i = 0; i < threads; i++) pthread_join(th[i], NULL);
    double el = since_ns(&t0);
    int64_t done = 0, hits = 0, errs = 0;
    for (int i = 0; i < threads; i++) { done += args[i].done; hits += args[i].hits; errs += args[i].errs; }
    free(th); free(args);
    metrics_t m;
    m.ops = (int)done;
    m.qps = (double)done / (el / 1e9);
    m.avg_ns = el / (double)(done ? done : 1);
    m.p50_ns = m.p95_ns = m.p99_ns = 0;   /* not sampled in multithread path */
    m.errs = errs; m.hits = hits;
    m.hit_rate = (double)hits / (double)(done ? done : 1);
    m.warm = "hot"; m.api = "uint";
    return m;
}

static int g_conc_safe = 0;
static int64_t g_conc_done = 0;

static void *conc_run(void *arg) {
    targ_t *t = (targ_t *)arg;
    for (int i = 0; i < t->ops; i++) {
        int kind; uint64_t hi, lo;
        stream_next(&t->st, &kind, &hi, &lo);
        int hit = 0;
        int e = dispatch(t->ctx, kind, hi, lo, &hit);
        t->done++;
        if (is_real_error(e)) t->errs++;
    }
    return NULL;
}

static int concurrency_safe(qzdb_reader_t *ctx, uint64_t seed) {
    targ_t *args = calloc(CONC_THREADS, sizeof(targ_t));
    pthread_t *th = calloc(CONC_THREADS, sizeof(pthread_t));
    for (int i = 0; i < CONC_THREADS; i++) {
        stream_init(&args[i].st, D_HOT, M_MIXED, seed);
        args[i].ctx = ctx; args[i].ops = CONC_OPS;
        args[i].done = args[i].errs = 0;
    }
    for (int i = 0; i < CONC_THREADS; i++) pthread_create(&th[i], NULL, conc_run, &args[i]);
    for (int i = 0; i < CONC_THREADS; i++) pthread_join(th[i], NULL);
    int64_t done = 0, errs = 0;
    for (int i = 0; i < CONC_THREADS; i++) { done += args[i].done; errs += args[i].errs; }
    free(th); free(args);
    g_conc_done = done;
    return (errs == 0 && done == (int64_t)CONC_THREADS * CONC_OPS) ? 1 : 0;
}

/* ----------------------------------------------------------- parity */

static int parity_self_check(void) {
    printf("parity self-check ... ");
    int bad = 0;
    uint8_t buf[16];
    for (int d = 0; d < 4; d++) {
        for (int m = 0; m < 3; m++) {
            uint64_t seed = qzdb_bench_streams[d][m].seed;
            uint64_t want = qzdb_bench_streams[d][m].first1024_fnv1a;
            stream_t st; stream_init(&st, d, m, seed);
            uint64_t h = 0;
            int len;
            for (int i = 0; i < QZDB_BENCH_FINGERPRINT; i++) {
                int kind; uint64_t hi, lo;
                stream_next(&st, &kind, &hi, &lo);
                enc_query(kind, hi, lo, buf, &len);
                h = fnv1a(buf, len, h);
            }
            if (h != want) {
                printf("\n  MISMATCH %s.%s got=%llu want=%llu",
                       DIST_NAMES[d], MODE_NAMES[m],
                       (unsigned long long)h, (unsigned long long)want);
                bad++;
            }
        }
    }
    if (bad) { printf("\nFAILED\n"); return 0; }
    printf("OK (12/12 streams match bench_vectors.h)\n");
    return 1;
}

/* ----------------------------------------------------------- helpers */

static const char *repo_root(void) {
    /* tools/bench_vectors.h lives at <root>/multi-lang/tools/ */
    static char cwd[1024];
    if (!getcwd(cwd, sizeof(cwd))) return "";
    char tmp[1100];
    for (int i = 0; i < 8; i++) {
        snprintf(tmp, sizeof(tmp), "%s/multi-lang/tools/bench_vectors.h", cwd);
        if (access(tmp, R_OK) == 0) return cwd;
        char *p = strrchr(cwd, '/');
        if (!p) break;
        *p = '\0';
    }
    return "";
}

static const char *editions[][3] = {
    {"std_china",  "std",    "china"},
    {"max_global", "max",    "global"},
};

static char *find_db(const char *root, const char *edition, char *out, size_t n) {
    int found = -1;
    for (int e = 0; e < 2; e++) {
        if (strcmp(editions[e][0], edition) == 0) { found = e; break; }
    }
    if (found < 0) return NULL;
    const char *bases[] = {
        "%s/multi-lang/test_data_202608/%s/%s/qqzeng_ip_%s.qzdb",
        "%s/test_data_202608/%s/%s/qqzeng_ip_%s.qzdb",
    };
    char cand[1200];
    for (int b = 0; b < 2; b++) {
        snprintf(cand, sizeof(cand), bases[b], root,
                 editions[found][1], editions[found][2], edition);
        if (access(cand, R_OK) == 0) { snprintf(out, n, "%s", cand); return out; }
    }
    return NULL;
}

static void fmt_v4(uint32_t ip, char *buf) {
    sprintf(buf, "%u.%u.%u.%u",
            (ip >> 24) & 255, (ip >> 16) & 255, (ip >> 8) & 255, ip & 255);
}
static void fmt_v6(uint64_t hi, uint64_t lo, char *buf) {
    uint16_t g[8];
    for (int k = 0; k < 4; k++) g[k] = (hi >> (48 - 16 * k)) & 0xFFFF;
    for (int k = 0; k < 4; k++) g[4 + k] = (lo >> (48 - 16 * k)) & 0xFFFF;
    sprintf(buf, "%x:%x:%x:%x:%x:%x:%x:%x",
            g[0], g[1], g[2], g[3], g[4], g[5], g[6], g[7]);
}

static char *cpu_model(void) {
    static char brand[256];
#if defined(__APPLE__)
    size_t len = sizeof(brand);
    if (sysctlbyname("machdep.cpu.brand_string", brand, &len, NULL, 0) == 0)
        return brand;
#endif
    return "unknown";
}

/* ----------------------------------------------------------- JSON emit */

static void emit_metrics(FILE *f, const char *key, metrics_t *m) {
    fprintf(f,
        "    \"%s\": {\"ops\":%d,\"qps\":%.0f,\"avg_ns\":%.1f,"
        "\"p50_ns\":%lld,\"p95_ns\":%lld,\"p99_ns\":%lld,"
        "\"errors\":%lld,\"hits\":%lld,\"hit_rate\":%.4f",
        key, m->ops, m->qps, m->avg_ns,
        (long long)m->p50_ns, (long long)m->p95_ns, (long long)m->p99_ns,
        (long long)m->errs, (long long)m->hits, m->hit_rate);
    if (m->warm && *m->warm) fprintf(f, ",\"warm\":\"%s\"", m->warm);
    if (m->api  && *m->api)  fprintf(f, ",\"api\":\"%s\"", m->api);
    fprintf(f, "}");
}

/* ----------------------------------------------------------- main */

int main(int argc, char **argv) {
    (void)argc; (void)argv;
    if (getenv("BENCH_OPS")) {
        int v = atoi(getenv("BENCH_OPS"));
        if (v > 0) g_ops = v;
    }
    const char *ed_list[8]; int ned = 0;
    if (getenv("BENCH_EDITIONS")) {
        static char edbuf[512];
        strncpy(edbuf, getenv("BENCH_EDITIONS"), sizeof(edbuf) - 1);
        edbuf[sizeof(edbuf) - 1] = '\0';
        char *tk = strtok(edbuf, ",");
        while (tk && ned < 8) { ed_list[ned++] = tk; tk = strtok(NULL, ","); }
    } else {
        ed_list[ned++] = "std_china";
        ed_list[ned++] = "max_global";
    }

    const char *root = repo_root();
    if (!*root) { fprintf(stderr, "cannot locate repo root\n"); return 1; }

    build_pools();
    if (!parity_self_check()) return 1;

    char repdir[1200];
    snprintf(repdir, sizeof(repdir), "%s/multi-lang/bench_reports", root);
    mkdir(repdir, 0755);

    char ts[64]; time_t now = time(NULL);
    strftime(ts, sizeof(ts), "%Y-%m-%dT%H:%M:%S%z", localtime(&now));
    int cores = (int)sysconf(_SC_NPROCESSORS_ONLN);

    for (int e = 0; e < ned; e++) {
        const char *edition = ed_list[e];
        char dbpath[1200];
        if (!find_db(root, edition, dbpath, sizeof(dbpath))) {
            printf("[SKIP] %s: db not found\n", edition);
            continue;
        }
        qzdb_reader_t ctx;
        if (qzdb_init(&ctx, dbpath) != 0) {
            printf("[SKIP] %s: open failed\n", edition);
            continue;
        }
        struct stat st; stat(dbpath, &st);
        printf("\nedition %s: %s (%lld bytes)\n", edition, dbpath, (long long)st.st_size);

        int safe = concurrency_safe(&ctx, qzdb_bench_streams[D_HOT][M_MIXED].seed);
        g_conc_safe = safe;
        printf("  concurrency_safe(%dx%dk): %s (done=%lld)\n",
               CONC_THREADS, CONC_OPS / 1000, safe ? "true" : "false",
               (long long)g_conc_done);

        char out[1300];
        snprintf(out, sizeof(out), "%s/c_%s.json", repdir, edition);
        FILE *f = fopen(out, "w");
        if (!f) { fprintf(stderr, "open %s: %s\n", out, strerror(errno)); qzdb_free(&ctx); continue; }
        fprintf(f, "{\n");
        fprintf(f, "  \"contract\": \"QZDB_BENCH_CONTRACT v1.0\",\n");
        fprintf(f, "  \"language\": \"c\",\n");
        fprintf(f, "  \"sdk_version\": \"multi-lang/c (qzdb_reader.c)\",\n");
        fprintf(f, "  \"timestamp\": \"%s\",\n", ts);
        fprintf(f, "  \"seed\": %llu,\n", (unsigned long long)QZDB_BENCH_MASTER_SEED);
        fprintf(f, "  \"db\": {\"path\": \"%s\", \"edition\": \"%s\", \"bytes\": %lld, \"hash\": \"crc32:n/a\"},\n",
                dbpath, edition, (long long)st.st_size);
        fprintf(f, "  \"environment\": {\n");
        fprintf(f, "    \"cpu\": \"%s\",\n", cpu_model());
        fprintf(f, "    \"cores\": %d,\n", cores);
        fprintf(f, "    \"os\": \"darwin arm64\",\n");
        fprintf(f, "    \"compiler\": \"Apple clang\",\n");
        fprintf(f, "    \"runtime\": \"native\",\n");
        fprintf(f, "    \"bench_contract\": \"v1.0\",\n");
        fprintf(f, "    \"note\": \"Fill-only immutable lock-free decode cache; shared-reader thread scaling is the headline metric.\"\n");
        fprintf(f, "  },\n");

        fprintf(f, "  \"distributions\": {\n");
        int first_d = 1;
        for (int d = 0; d < 4; d++) {
            if (!first_d) fprintf(f, ",\n");
            first_d = 0;
            fprintf(f, "    \"%s\": {\n", DIST_NAMES[d]);
            int first_m = 1;
            for (int m = 0; m < 3; m++) {
                uint64_t seed = qzdb_bench_streams[d][m].seed;
                metrics_t cold = run_single(&ctx, d, m, seed,
                                            g_ops < COLD_OPS ? g_ops : COLD_OPS, 1);
                cold.warm = "cold";
                run_single(&ctx, d, m, seed, g_ops < WARMUP_OPS ? g_ops : WARMUP_OPS, 0);
                metrics_t hot = run_single(&ctx, d, m, seed, g_ops, 1);
                hot.warm = "hot";
                int tcfgs[] = {1, 2, 4, 8, 16};
                metrics_t th[5];
                for (int ti = 0; ti < 5; ti++)
                    th[ti] = run_multi(&ctx, d, m, seed, tcfgs[ti], g_ops);
                if (!first_m) fprintf(f, ",\n");
                first_m = 0;
                fprintf(f, "      \"%s\": {\n", MODE_NAMES[m]);
                emit_metrics(f, "cold", &cold);
                fprintf(f, ",\n");
                emit_metrics(f, "hot", &hot);
                fprintf(f, ",\n      \"threads\": {");
                for (int ti = 0; ti < 5; ti++) {
                    char tk[8]; snprintf(tk, sizeof(tk), "%d", tcfgs[ti]);
                    if (ti) fprintf(f, ", ");
                    emit_metrics(f, tk, &th[ti]);
                }
                fprintf(f, "}");
                fprintf(f, "\n      }");
                double scl = th[4].qps / (th[0].qps + 1e-9);
                printf("  %-11s.%-6s hot QPS=%12.0f p50=%6lldns p99=%7lldns 1T=%12.0f 16T=%12.0f (%.1fx) hit=%.1f%%\n",
                       DIST_NAMES[d], MODE_NAMES[m], hot.qps, (long long)hot.p50_ns,
                       (long long)hot.p99_ns, th[0].qps, th[4].qps, scl,
                       hot.hit_rate * 100.0);
            }
            fprintf(f, "\n    }");
        }
        fprintf(f, "\n  },\n");

        /* string round-trip on hot.mixed */
        {
            stream_t st; stream_init(&st, D_HOT, M_MIXED,
                                     qzdb_bench_streams[D_HOT][M_MIXED].seed);
            char sbuf[64];
            int64_t *lat = malloc((g_ops / LAT_EVERY + 1) * sizeof(int64_t));
            int lcnt = 0; int64_t serr = 0;
            struct timespec t0; now_ns(&t0);
            for (int i = 0; i < g_ops; i++) {
                int kind; uint64_t hi, lo;
                stream_next(&st, &kind, &hi, &lo);
                if (kind == 0) fmt_v4((uint32_t)hi, sbuf);
                else fmt_v6(hi, lo, sbuf);
                qzdb_geo_info_t info;
                if (i % LAT_EVERY == 0) {
                    struct timespec a; now_ns(&a);
                    if (is_real_error(qzdb_find(&ctx, sbuf, &info))) serr++;
                    int64_t dt = (int64_t)since_ns(&a);
                    if (lcnt < g_ops / LAT_EVERY + 1) lat[lcnt++] = dt;
                } else {
                    if (is_real_error(qzdb_find(&ctx, sbuf, &info))) serr++;
                }
            }
            double el = since_ns(&t0);
            metrics_t srt;
            srt.ops = g_ops; srt.qps = (double)g_ops / (el / 1e9);
            srt.avg_ns = el / (double)g_ops;
            srt.p50_ns = pct(lat, lcnt, 0.50); srt.p95_ns = pct(lat, lcnt, 0.95);
            srt.p99_ns = pct(lat, lcnt, 0.99);
            srt.errs = serr; srt.hits = 0; srt.hit_rate = 0;
            srt.warm = "hot"; srt.api = "string";
            /* emit_metrics() writes the `"<key>": {...}` pair itself — do NOT
               also print the key here, that yields a duplicated key and
               invalid JSON ({"mixed": "mixed": {...}}). */
            fprintf(f, "  \"string_roundtrip\": {\"hot\": {");
            emit_metrics(f, "mixed", &srt);
            fprintf(f, "}},\n");
            free(lat);
            printf("  %-11s.%-6s STRING round-trip QPS=%12.0f p99=%7lldns\n",
                   "hot", "mixed", srt.qps, (long long)srt.p99_ns);
        }

        fprintf(f, "  \"concurrency_safe\": %s,\n", safe ? "true" : "false");
        fprintf(f, "  \"concurrency_done\": %lld,\n", (long long)g_conc_done);
        fprintf(f, "  \"concurrency_spec\": \"%d threads x %d ops shared reader\"\n",
                CONC_THREADS, CONC_OPS);
        fprintf(f, "}\n");
        fclose(f);
        printf("  wrote %s\n", out);
        qzdb_free(&ctx);
    }
    return 0;
}
